#!/usr/bin/env bash

##
# Better `git clone`
# Clones a repository, cds into it, and opens it in $EDITOR|$GUI_EDITOR.
#
# USAGE
#   $ clone <repo-name>
#     .. git clone git@github.com:<your-username>/<repo-name>.git <repo-name>
#     .. cd <repo-name>
#     .. $EDITOR .
#
#   $ clone <username>/<repo-name>
#     .. git clone git@github.com:<username>/<repo-name>.git <repo-name>
#     .. cd <repo-name>
#     .. $EDITOR .
#
#   $ clone git@github.com:<username>/<repo-name>.git
#     .. git clone git@github.com:<username>/<repo-name>.git <repo-name>
#     .. cd <repo-name>
#     .. $EDITOR .
#
# CREDIT
#	Originally taken from addyosmani/dotfiles
##

if [ $# -eq 0 ]; then
	echo -e 'Better `git clone`. Clones a repository, cds into it, and opens it in $EDITOR|$GUI_EDITOR.\n'
	echo -e 'USAGE\n  $ clone <repo-url|username/repo-name|own-repo-name>'
	exit 0
fi

username=$GITHUB_USERNAME

if [[ -n $GUI_EDITOR ]]; then
	edit=$GUI_EDITOR
else
	edit=${EDITOR:-vim}
fi

# $ clone <repo-url>
if [[ ${1:0:4} == 'http' || ${url:0:3} == 'git' ]]; then
	url=$1

	# Parse repo name from URL for directory name
	repo=$(echo $url | awk -F/ '{print $NF}' | sed -e 's/.git$//')

# $ clone <username>/<repo-name>
elif [[ $1 =~ "/"  ]]; then
	username=$(dirname "$1")
	repo=$(basename "$1")
	url="git@github.com:$username/$repo.git"

# $ clone <repo-name>
else
	repo=$1
	url="git@github.com:$username/$repo"
fi

git clone "$url" "$repo" && cd "$repo" && $edit .
