#!/usr/bin/env bash

##
# Better `git clone`
# Clones a repository, cds into it, and opens it in my editor.
#
# USAGE
#	$ clone things
#	  .. git clone git@github.com:<your-username>/things.git things
#	  .. cd things
#	  .. atom .
#
#	$ clone yeoman generator
#	  .. git clone git@github.com:yeoman/generator.git generator
#	  .. cd generator
#	  .. atom .
#
#	$ clone git@github.com:<username>/<repo-name>.git
#	  .. git clone git@github.com:<username>/<repo-name>.git <repo-name>
#	  .. cd <repo-name>
#	  .. atom .
#
# CREDIT
#	Forked from addyosmani/dotfiles
##

if [ $# -eq 0 ]; then
	echo 'USAGE: $ clone <repo-url|own-repo-name|username/repo-name>'
	exit 1
fi

username=$GITHUB_USERNAME

if [[ -n $GUI_EDITOR ]]; then
	edit=$GUI_EDITOR
else
	edit='vim'
fi

# $ clone <repo-url>
if [[ ${1:0:4} == 'http' || ${url:0:3} == 'git' ]]; then
	url=$1

	# Parse repo name from URL for directory name
	repo=$(echo $url | awk -F/ '{print $NF}' | sed -e 's/.git$//')

# $ clone <username>/<repo-name>
elif [[ $1 =~ "/"  ]]; then
	username=`dirname $1`
	repo=`basename $1`
	url="git@github.com:$username/$repo.git"

# $ clone <repo-name>
else
	repo=$1
	url="git@github.com:$username/$repo"
fi

git clone $url $repo && cd $repo && $edit .
