#!/usr/bin/env bash

##
# Goes GitHub and related links
#
# USAGE
#	$ gh
#	  .. goes https://github.com
#	$ gh me
#	  .. goes https://github.com/$GITHUB_USERNAME
#	$ gh webpack
#	  .. goes first Google "webpack GitHub" result
##

keyword=$1
url="https://www.google.com/search?q=$keyword%20GitHub&btnI="

if [ $# -eq 0 ]; then
	url="https://github.com"
elif [ $keyword == "me" ]; then
	url="https://github.com/$GITHUB_USERNAME"
fi

if [[ $(uname) = 'Darwin' ]]; then
	open -a Google\ Chrome $url

elif [[ $(uname) = 'Linux' ]]; then
	google-chrome $url
fi
