#!/usr/bin/env bash

##
# Toggles environment according to my setup
##

if [[ -f "$HOME/.config/isserver.kutsan" ]]; then
	rm "$HOME/.config/isserver.kutsan"

else
	touch "$HOME/.config/isserver.kutsan"
fi
