#!/usr/bin/env bash

##
# Easy file sharing from the command line via https://transfer.sh (files stored for 14 days)
#
# USAGE
#	$ transfer <file>
##

if [ $# -eq 0 ]; then
	echo -e "Easy file sharing from the command line via https://transfer.sh (files stored for 14 days)\n"
	echo -e "USAGE\n  $ transfer <file>"
	exit 1
fi

tmpfile=$( mktemp -t transferXXX )

if tty -s; then
	basefile=$(basename "$1" | sed -e 's/[^a-zA-Z0-9._-]/-/g')
	curl --progress-bar --upload-file "$1" "https://transfer.sh/$basefile" >> $tmpfile

else
	curl --progress-bar --upload-file "-" "https://transfer.sh/$1" >> $tmpfile
fi

cat $tmpfile
rm -f $tmpfile
