#!/usr/bin/env bash

##
# Updates various environment, software and packages
##

info() {
	echo -e "\n\033[32m  info \033[0m$1\n"
}

if [[ $(uname) = 'Darwin' ]] 2> /dev/null; then
	info 'Homebrew'
	if which brew 2> /dev/null; then
		brew update
		brew upgrade
		brew cleanup
	fi

elif [[ $(uname -o) = 'Android' ]] 2> /dev/null; then
	info 'Packages'
	apt upgrade
	apt autoremove
	apt autoclean

elif [[ $(uname) = 'Linux' ]] 2> /dev/null; then
	info 'Packages'
	sudo apt upgrade
	sudo apt autoremove
	sudo apt autoclean
fi

info 'npm'
npm update npm -g
npm update -g

info 'Oh My Zsh'
sh $ZSH/tools/upgrade.sh

info 'VimPlug & Vim Plugins'
curl -Lo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +PlugUpdate +qa
